name: Test Cases
on:
  push:
    branches: Lab11

jobs:
  TestCases:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: "actions/checkout@v3"
      
      - name: Compile & Execute
        run: |
          cd $GITHUB_WORKSPACE/
          kotlin TestCases.kt
