name: TestCases
on:
  push:
   branches: Lab11
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Download Kotlin Compiler
        run: |
          wget -O kotlinc.tar.gz "https://github.com/JetBrains/kotlin/releases/download/v1.5.31/kotlin-compiler-1.5.31.zip"
          mkdir -p ~/kotlin
          tar -xzf kotlinc.tar.gz -C ~/kotlin --strip-components=1
      - name: Build with Kotlin
        run: |
          ~/kotlin/bin/kotlinc -include-runtime -d app.jar ./*.kt$
