name: Kotlin Tests
on:
  push:
   branches: Lab11
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
      - name: Set up Kotlin
        uses: actions/setup-kotlin@v1
        with:
          kotlin-version: '1.5.31'
      - name: Build with Gradle
        run: ./gradlew build
      - name: Test with Gradle
        run: ./gradlew test
